export enum TaskType {
	NONE = "NONE",
	FOLLOW_FROM_HASHTAG = "FOLLOW_FROM_HASHTAG",
	FOLLOW_TOP_ACCOUNTS_FROM_POLAND = "FOLLOW_TOP_ACCOUNTS_FROM_POLAND",
	FOLLOW_NEW_INCOMERS_THEN_FOLLOW_TOP_ACCOUNTS_FROM_POLAND = "FOLLOW_NEW_INCOMERS_THEN_FOLLOW_TOP_ACCOUNTS_FROM_POLAND"
}
