export enum LogType {
	NONE = "NONE",
	TASK_STARTED = "TASK_STARTED",
	TASK_ENDED = "TASK_ENDED",
	NEW_FOLLOW = "NEW_FOLLOW",
	NEW_UNFOLLOW = "NEW_UNFOLLOW",
	INVALID_OPERATION = "INVALID_OPERATION"
}
